package org.tetawex.ecf.presentation

const val VIEWPORT_WIDTH = 1440f
const val VIEWPORT_HEIGHT = 2560f

const val DEFAULT_PADDING = 80f
const val DEFAULT_PADDING_HALF = DEFAULT_PADDING / 2
const val DEFAULT_PADDING_QUARTER = DEFAULT_PADDING / 4

const val VIEWPORT_WIDTH_MINUS_PADDING = VIEWPORT_WIDTH - DEFAULT_PADDING * 2

const val PAUSE_BUTTON_WIDTH = VIEWPORT_WIDTH_MINUS_PADDING
const val PAUSE_BUTTON_HEIGHT = 252f
const val PAUSE_BUTTON_PAD = DEFAULT_PADDING_HALF
const val PAUSE_BUTTON_FONT_SCALE = 1f

const val BUTTON_WIDTH = VIEWPORT_WIDTH_MINUS_PADDING
const val BUTTON_HEIGHT = 252f
const val BUTTON_PAD = DEFAULT_PADDING_HALF
const val BUTTON_FONT_SCALE = 1f

const val MODAL_BUTTON_PADDING = DEFAULT_PADDING

const val MANA_LABEL_FONT_SCALE = 1f
const val SCORE_LABEL_FONT_SCALE = 1f